inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'config/routes.rb'
    - 'lib/tasks/**/*'
    - 'test/**/*'
    - 'app/views/sitemaps/**/*'
    - 'config/environments/development.rb'

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: true
  EnforcedStyle: compact

Style/FormatStringToken:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

