inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'config/routes.rb'
    - 'lib/tasks/**/*'
    - 'test/**/*'
    - 'app/views/sitemaps/**/*'
    - 'config/environments/development.rb'
Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 10

Style/IfUnlessModifier:
  Enabled: false