ARG RUBY_VERSION=4.0.0
FROM ruby:${RUBY_VERSION}

ENV LANG=C.UTF-8 TZ=Asia/Tokyo

# PostgreSQLのクライアントライブラリRailsのイメージに含める
# https://wiki.postgresql.org/wiki/Apt
RUN apt-get update \
  && apt-get install -y curl ca-certificates \
  && install -d /usr/share/postgresql-common/pgdg \
  && curl -o /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc --fail \
    https://www.postgresql.org/media/keys/ACCC4CF8.asc \
  && . /etc/os-release \
  && echo "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt ${VERSION_CODENAME}-pgdg main" \
    > /etc/apt/sources.list.d/pgdg.list \
  && apt-get update \
  && apt-get install -y postgresql-client-18 \
  && rm -rf /var/lib/apt/lists/*
